name: Deployment

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'tag version'
        required: true
      environment:
        description: 'environment [dev, qa, prod]'
        required: true

jobs:
  deploy-dev:
    if: github.event.inputs.environment == 'dev'
    runs-on: ubuntu-latest
    env:
      ENV: ${{ github.event.inputs.environment }}
      TF_VAR_repository_version: ${{ github.event.inputs.version }}
    steps:
      - run: echo "will deploy to DEV!"

  deploy-prod:
    if: github.event.inputs.environment == 'prod'
    runs-on: ubuntu-latest
    environment:
      name: prod
    env:
      ENV: ${{ github.event.inputs.environment }}
      TF_VAR_repository_version: ${{ github.event.inputs.version }}
    steps:
      - run: echo "will deploy to PROD!"
