name: master release

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-java@master
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Compile
        run: make compile
      - uses: actions/upload-artifact@master
        with:
          name: build
          path: build

  publish-artifact:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - name: ls
        run: ls -la
      - name: ls2
        run: ls -la ./build/libs

